name: Python CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - name: Install libxcb-xinerama0
      run: sudo apt-get update && sudo apt-get install libxcb-xinerama0 && sudo apt remove qtchooser
    - uses: actions/checkout@v2
    - name: Install Qt5/Qt6
      uses: yaqti/install-qt-action@v1
      with:
        qt-version: '5.15.2'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install -U --pre yt-dlp
        conda install -c conda-forge opencv
    - name: Run Python script
      run: |
        python download.py https://www.youtube.com/watch?v=SckYas-Uy24
