name: Python CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - name: Install libxcb-xinerama0
      run: sudo apt-get update && sudo apt-get install libxcb-xinerama0 && sudo apt remove qtchooser
    - uses: actions/checkout@v2
    - name: Setup OpenCV
      uses: Dovyski/setup-opencv-action@v1.1
      with:
        opencv-version: '4.0.0'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install -U --pre yt-dlp
        pip install opencv-python --upgrade
        conda install -c conda-forge opencv
    - name: Run Python script
      run: |
        python download.py https://www.youtube.com/watch?v=SckYas-Uy24
