name: Python CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -U --pre yt-dlp
    - name: Run Python script
      run: |
        python download.py https://www.youtube.com/watch?v=SckYas-Uy24
